# Generated by Django 3.2.7 on 2021-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=26)),
                ('Fname', models.CharField(max_length=30)),
                ('Phno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
