# Generated by Django 3.2.7 on 2021-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('empName', models.CharField(max_length=70)),
                ('empEmail', models.EmailField(max_length=70)),
                ('empMobile', models.IntegerField(max_length=15)),
            ],
        ),
    ]
