# Generated by Django 3.2.7 on 2021-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10)),
                ('PhoneNo', models.IntegerField()),
                ('Email', models.EmailField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Country', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=100)),
                ('UploadImage', models.ImageField(upload_to='Images')),
                ('Password', models.CharField(max_length=10)),
                ('Agree_Terms', models.BooleanField(max_length=10)),
            ],
        ),
    ]
