# Generated by Django 3.2.7 on 2021-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeConnect', '0002_alter_user_agree_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UploadImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
