# Generated by Django 3.2.7 on 2021-09-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeConnect', '0005_user_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UploadImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
