# Generated by Django 3.2.7 on 2021-09-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('TelNo', models.IntegerField()),
                ('HighSchoolName', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=100)),
                ('Yourlevel', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
            ],
        ),
    ]
