# Generated by Django 3.2.7 on 2021-09-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentcrudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='DOB',
        ),
    ]
