# Generated by Django 3.2.7 on 2021-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stid', models.IntegerField()),
                ('Fname', models.CharField(max_length=30)),
                ('Mname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Phno', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Company', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
            ],
        ),
    ]
