# Generated by Django 3.2.7 on 2021-09-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model_forms',
            new_name='model_forms_model',
        ),
    ]
